name: simple_async_executor
description: Basic async executor for Dart and Flutter
version: 0.0.1+2
homepage: https://github.com/smsimone/simple_async_executor
repository: https://github.com/smsimone/simple_async_executor

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.19.5

flutter:
